param_:
  test: 1
  # map:
  #   size:
  #     x: 50.0
  #     y: 50.0
  #     z: 20.0
  #   resolution: 0.2
  # geometry_env:
  #   type: balls  # balls, cones,  arcs
  #   balls:
  #     num_balls: 100
  #     radius:
  #       min: 0.5
  #       max: 1.0
  #   cones:
  #     num_cones: 100
  #     radius:
  #       min: 0.5
  #       max: 1.0
  #     height:
  #       min: 1.0
  #       max: 2.0
  #   arcs:
  #     num_arcs: 100
  #     radius:
  #       min: 0.5
  #       max: 1.0
  #     height:
  #       min: 1.0
  #       max: 2.0
  #     angle:
  #       min: 30.0
  #       max: 180.0  
  
