param_:
  map:
    size:
      x: 50.0
      y: 50.0
      z: 20.0
    resolution: 0.2
  geometroy_env:
    balls:
      num_balls: 50
      radius:
        min: 2.5
        max: 5.0
    cones:
      num_cones: 50
      radius:
        min: 0.51
        max: 5.01
      height:
        min: 2.01
        max: 5.01
    boxes:
      num_boxes: 10
      size:
        min: 1.0
        max: 2.0
          


  
