param_:
  map:
    size:
      x: 50.0
      y: 50.0
      z: 20.0
    resolution: 0.2
  geometry_env:
    type: cylinder
  
  
  generateCylinerPcd:
    num_cylinders: 1000
    points_per_circle: 1000
    radius:
      min: 0.8
      max: 1.0
    size:
      x: 20.0
      y: 20.0
      z: 10.0
    z_step: 0.01