param_:
  map:
    size:
      x: 50.0
      y: 50.0
      z: 50.0
    resolution: 5.0
  geometroy_env:
    boxes:
      num_boxes: 200
      size:
        min: 1.0
        max: 2.0
      speed:
        min: 0.5
        max: 1.0
          
          


  
