param_:
  map:
    size:
      x: 100.0
      y: 100.0
      z: 100.0
    resolution: 3.0
  geometroy_env:
    boxes:
      num_boxes: 200
      size:
        min: 0.5
        max: 1.0
      speed:
        min: 0.5
        max: 1.0
          
          


  
