param_:
  map:
    size:
      x: 50.0
      y: 50.0
      z: 50.0
    resolution: 4.0
  geometroy_env:
    boxes:
      num_boxes: 1000
      size:
        min: 0.25
        max: 1.0
      speed:
        min: 1.0
        max: 2.0
          
          


  
